base:
  transnet_shotdetection:
    color: "#ff9999"
    shape: box
  asr:
    color: "#69cfd3"
    shape: box
  span:
    color: "#66cc66"
    shape: dot
nodes:
  instructblip_daytime:
    plugin_type: query
    color: "#ffffff"
    shape: dot
    relation: 
      target: shot
      weight: mean
      threshold: 0.5
  instructblip_environment:
    plugin_type: query
    color: "#ffffff"
    shape: dot
    relation: 
      target: shot
      weight: mean
      threshold: 0.5
  instructblip_events:
    plugin_type: query
    color: "#ffffff"
    shape: dot
    relation: 
      target: shot
      weight: mean
      threshold: 0.5
  instructblip_weather:
    plugin_type: query
    color: "#ffffff"
    shape: dot
    relation: 
      target: shot
      weight: mean
      threshold: 0.5