base:
  transnet_shotdetection:
    color: "#ff9999"
    shape: box
  asr:
    color: "#69cfd3"
    shape: box
  span:
    color: "#66cc66"
    shape: dot
nodes:
  camera_size_classification:
    type: attribute
    attribute: 
      target: shot
      value: mean
  instructblip_daytime:
    type: node
    plugin_type: query
    color: "#ffffff"
    shape: dot
    relation: 
      target: shot
      weight: mean
      threshold: 0.5
  instructblip_environment:
    type: node
    plugin_type: query
    color: "#ffffff"
    shape: dot
    relation: 
      target: shot
      weight: mean
      threshold: 0.5
  instructblip_events:
    type: node
    plugin_type: query
    color: "#ffffff"
    shape: dot
    relation: 
      target: shot
      weight: mean
      threshold: 0.5
  instructblip_weather:
    type: node
    plugin_type: query
    color: "#ffffff"
    shape: dot
    relation: 
      target: shot
      weight: mean
      threshold: 0.5
  